name: next_configui

services:
  ubcore:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      - pocketbase
    networks:
      - main-net
