name: pb_configdb

networks:
  main-net:
    external: false

services:
  pocketbase:
    build: .
    volumes:
      - ./pb_data:/app/pb_data
    ports:
      - 8090:8090
    networks:
      - main-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8090/api/health"]
      interval: 5s
      timeout: 2s
      retries: 10
